bigweb/blueprints/auth.py
from flask import Blueprint,render_template,redirect,url_for,flash
from bigweb.forms import RegisterForm,LoginForm,ForgetPasswordForm,ResetPasswordForm
from bigweb.models import User
from bigweb.extensions import db
from flask_login import login_user,logout_user,current_user,login_required
from bigweb.utils import generate_token,validate_token
from bigweb.settings import Operation
from bigweb.emails import send_confirm_email,send_password_email


auth_bp = Blueprint("auth",__name__)


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        email = register_form.email.data
        username = register_form.username.data
        password = register_form.password.data


        user = User(email=email, username=username)
        user.set_password(password)


        db.session.add(user)
        db.session.commit()

        token = generate_token(user=user, operation=Operation.CONFIRM)
        send_confirm_email(user=user,token=token)

        flash("已经向您的邮箱发送了一份验证邮件，赶快去验证吧")
        login_user(user)
        return redirect(url_for("main.index"))
    return render_template("auth/register.html", register_form=register_form)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        email = login_form.email.data.lower()
        password = login_form.password.data
        remember = login_form.remember.data
        user = User.query.filter_by(email=email).first()
        if user:
            if user.validate_password(password):
                login_user(user,remember)
                return redirect(url_for("main.index"))
            else:
                flash("密码错误，请重新输入")
        else:
            flash("该邮箱没有注册，请先注册")
    return render_template("auth/login.html", login_form=login_form)



@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth_bp.route("/confirm/<token>")
def confirm(token):
    # if not current_user.is_authenticated:
    #     flash("您可以在个人中心进行邮箱验证")
    #     return redirect(url_for("auth.login"))
    if current_user.confirmed == True:
        return redirect(url_for("main.index"))
    if validate_token(user=current_user,token=token,operation=Operation.CONFIRM):
        flash("邮箱验证成功")
        return redirect(url_for("main.index"))
    else:
        flash("邮箱验证失败")
        return redirect(url_for("resend_email",operation=Operation.CONFIRM))



@auth_bp.route("/resend_email/<operation>")
@login_required
def resend_email(operation):
    token = generate_token(user=current_user,operation=operation)
    if operation == Operation.CONFIRM:
        send_confirm_email(user=current_user,token=token)
        flash("验证邮件已经发送，请赶快查收")
        return redirect(url_for("main.index"))
    elif operation == Operation.CHANGE_EMAIL:
        pass
    else:
        pass


@auth_bp.route("/forget-password",methods=["GET","POST"])
def forget_password():
    forgetpassword_form = ForgetPasswordForm()
    if forgetpassword_form.validate_on_submit():
        email = forgetpassword_form.email.data.lower()
        user = User.query.filter_by(email=email).first()
        if user:
            token = generate_token(user=user,operation=Operation.RESET_PASSWORD)
            send_password_email(user=user,token=token)
            flash("重置密码的验证邮件已经发往你的邮箱，请尽快验证")
            return redirect(url_for("auth.login"))
        flash("这个邮箱地址并没有在网站注册，请重新输入")
        return redirect(url_for("auth.forget_password"))
    return render_template("auth/forget_password.html", forgetpassword_form=forgetpassword_form)



@auth_bp.route("/reset-password/<token>",methods=["GET","POST"])
def reset_password(token):
    resetpassword_form = ResetPasswordForm()
    if resetpassword_form.validate_on_submit():
        email = resetpassword_form.email.data.lower()
        password = resetpassword_form.password.data
        user = User.query.filter_by(email=email).first()
        if user:
            if validate_token(user=user, token=token, operation=Operation.RESET_PASSWORD):
                user.set_password(password)
                db.session.commit()
                flash("密码设置成功，请您牢记您的密码")
                return redirect(url_for("auth.login"))
            else:
                flash("邮箱验证失败，请重新验证邮箱")
                return redirect(url_for("auth.forget_password"))
        else:
            flash("无效的邮箱，请重新输入")
            return redirect(url_for("auth.reset_password", token=token))
    return render_template("auth/reset_password.html",resetpassword_form=resetpassword_form)

bigweb/blueprints/user.py
from flask import Blueprint,render_template,redirect,url_for,current_app,make_response,flash
from bigweb.models import User,Post,Comment
from bigweb.forms import PostForm,PortraitForm
from flask_login import current_user
from bigweb.extensions import db,ckeditor
from flask import request,send_from_directory
from flask_ckeditor import upload_success,upload_fail
import os
from PIL import Image
from bigweb.utils import random_filename


user_bp = Blueprint("user",__name__)



@user_bp.route("/edit",methods=["GET","POST"])
def post_edit():
    post_form = PostForm()
    if request.method == "POST":
        title = post_form.title.data
        article = post_form.article.data
        post_sql = Post(title=title,article=article,user_id=current_user.id)
        db.session.add(post_sql)
        db.session.commit()
        return redirect(url_for("main.index"))
    return render_template("user/edit.html",post_form=post_form)



@user_bp.route("/get-file",defaults={'filename':'iii.jpg'})
@user_bp.route("/get-file/<filename>")
def get_file(filename):
    path = "/Users/adminkai/study_flakall/photo/bigweb/blueprints/upload"
    if filename is None:
        return send_from_directory("/Users/adminkai/study_flakall/photo/bigweb/static/image","iii.png")
    return send_from_directory(path,filename)


@user_bp.route("/upload",methods=["POST"])
def upload():
    f = request.files.get("upload")
    filename = random_filename(f.filename)

    extension = filename.split(".")[1].lower()
    if extension not in ["jpg","jpeg","gif","png","pneg","jpeg"]:
        return upload_fail(message="格式不支持")

    im = Image.open(f)
    size = im.size
    ima = im
    if size[0]>500:
        ima = im.resize((500,int(size[1]*(500/size[0]))))

    ima.save(os.path.join("/Users/adminkai/study_flakall/photo/bigweb/blueprints/upload",filename))
    url = url_for("user.get_file",filename=filename)
    return upload_success(url=url)




@user_bp.route("/portrait",methods=["GET","POST"])
def set_portrait():
    portrait_form = PortraitForm()
    if portrait_form.validate_on_submit():
        f = portrait_form.portrait.data
        filename = random_filename(f.filename)
        # f = Image.open(f)
        # f = f.resize((48,48))
        current_user.portrait = filename
        db.session.commit()
        f.save(os.path.join("/Users/adminkai/study_flakall/photo/bigweb/blueprints/upload",filename))
        flash("头像上传成功")
        return redirect(url_for("main.index"))
    return render_template("user/self.html",portrait_form=portrait_form)

bigweb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/base.css">
    {% block head %}{% endblock %}

</head>
<body background="../static/image/16.png" style="background-repeat:repeat;background-attachment:fixed;">
<div class="container-fluid">
    <div class="top">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for("main.index") }}" style="color: black;font-size: xx-large;">&nbsp;&nbsp;&nbsp;&nbsp;F-D-T</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">

                <li><a href="#" style="color: #f2f2f5;">Flask</a></li>
                <li><a href="#" style="color: #f2f2f5;">Django</a></li>
                <li><a href="#" style="color: #f2f2f5;">Tornado</a></li>

              </ul>
              <form class="navbar-form navbar-left">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                      <li><a href="{{ url_for("user.post_edit") }}" style="color: #f2f2f5;">发帖</a></li>
                      <li><a href="{{ url_for("user.set_portrait") }}" style="color: #f2f2f5;">{{ current_user.username }}</a></li>
                      <li><a href="{{ url_for("auth.logout") }}" style="color: #f2f2f5;">注销</a></li>
                  {% else %}
                     <li><a href="{{ url_for("auth.login") }}" style="color: #f2f2f5;">登录</a></li>
                     <li><a href="{{ url_for("auth.register") }}" style="color: #f2f2f5;">注册</a></li>
                  {% endif %}

              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class="main">
        <div class="main-left"></div>

        <div class="main-betwen">
            <div class="main-main">

                {% for message in get_flashed_messages() %}
                     <div class="alert alert-warning alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                     </div>
                {% endfor %}

                {% block body %}{% endblock %}
            </div>
            <div class="main-two">
                {% block bodytwo %}{% endblock %}
            </div>
        </div>

        <div class="main-right"></div>

    </div>
    <div class="foot"></div>
</div>


{% block script %}
    {{ moment.locale(auto_detect=True) }}
    {{ moment.include_moment() }}
    {{ moment.include_jquery() }}
{% endblock %}

</body>
</html>

bigweb/templates/macros.html
{% macro field_form(field) %}

    {{ field.label }}
    {{ field(**kwargs) }}
    {% if field.errors %}
        {% for error in field.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    {% endif %}

{% endmacro %}