bigweb/apis/v1/main.py
from flask import Blueprint,jsonify
from bigweb import create_app
from bigweb.models import Post


api_v1_main = Blueprint("api_v1_main",__name__)




@api_v1_main.route("/postss",methods=["GET"])
def getposts():
    post = Post.query.first()
    return jsonify({
        "title" : post.title,
        "body" : post.article,
        "timestamp" : post.timestamp
    })

bigweb/blueprints/main.py
from flask import Blueprint,render_template,redirect,url_for,request,jsonify
from bigweb.decorate import confirm_required
from flask_login import login_required
from flask_login import current_user
from bigweb.models import User,Role,Permission,Post,Comment
from bigweb.extensions import db
from bigweb.forms import CommentForm

main_bp = Blueprint("main",__name__)


@main_bp.route("/")
def index():
    # db.drop_all()
    # db.create_all()
    posts = reversed(Post.query.all())

    # userr = db.session.execute("""SELECT email FROM user
    #     WHERE email='17640175486@163.com'
    # """).first()
    # print("**********************************")
    # print(userr)

    return render_template("main/index.html",posts=posts)



@main_bp.route("/post/<int:post_id>",methods=["GET","POST"])
def post(post_id):
    comment_form = CommentForm()
    if request.method == "POST":
        print("**********************")
        print(post_id)

        data = request.get_json()
        if data is None or data["comment"].strip() == "":
            return "没有获取数据"
        comment = data["comment"]

        print("******************************************")
        print("获取到了数据")
        print(comment)
        comment_sql = Comment(comment=comment,post_id=post_id,user_id=current_user.id)
        db.session.add(comment_sql)
        db.session.commit()
        return """
                        <div class="comment-list">
                    <div class="comment-list-image"><img src="{{ url_for("user.get_file",filename=comment.post.user.portrait) }}" alt=""></div>
                    <div class="comment-list-body">
                        <div class="comment-list-top">
                            <p class="comment-p"><a href="#">{}👌🌹：</a>{}</p>
                        </div>
                        <div class="comment-list-add">
                            <span class="comment-list-time">{{ comment.timestamp }}</span>
                            <button class="comment-list-reply">回复&nbsp;|&nbsp;👍 点赞</button>
                        </div>
                    </div>
                </div>
        """.format(comment_sql.user.username,comment_sql.comment),200
    post = Post.query.get(post_id)
    return render_template("main/post.html",post=post,comment_form=comment_form)

@main_bp.route("/comment-ajax/<int:post_id>",methods=["POST"])
def comment_ajax(post_id):
    data = request.get_json()
    if data is None or data["comment"].strip() == "":
        return "没有获取数据"
    comment = data["comment"]
    comment_sql = Comment(comment=comment, post_id=post_id, user_id=current_user.id)
    db.session.add(comment_sql)
    db.session.commit()
    return """
                    <div class="comment-list">
                <div class="comment-list-image"><img src="{}" alt=""></div>
                <div class="comment-list-body">
                    <div class="comment-list-top">
                        <p class="comment-p"><a href="#">{}👌🌹：</a>{}</p>
                    </div>
                    <div class="comment-list-add">
                        <span class="comment-list-time">{}</span>
                        <button class="comment-list-reply">回复&nbsp;|&nbsp;👍 点赞</button>
                    </div>
                </div>
            </div>
    """.format(url_for("user.get_file",filename=comment_sql.post.user.portrait),comment_sql.user.username, comment_sql.comment, comment_sql.timestamp), 200

bigweb/templates/main/index.html
{% extends "base.html" %}

{% block head %}

{% endblock %}


{% block body %}
            <div class="question-list">

                <div class="index-title">
                    <h2>人生苦短，我用python</h2>
                    <p>
                        优美胜于丑陋 &nbsp; &nbsp;
                        显式胜于隐式 &nbsp;&nbsp;
                        简单胜于复杂 &nbsp;&nbsp;
                        复杂胜于难懂 &nbsp;&nbsp;
                        扁平胜于嵌套 &nbsp;&nbsp;
                        稀疏胜于紧密 &nbsp;&nbsp;
                        可读性应当被重视 &nbsp;&nbsp;
                        尽管实用性会打败纯粹性，特例也不能凌驾于规则之上 &nbsp;&nbsp;
                        不要忽略任何错误，除非你确认要这么做 &nbsp;&nbsp;
                        面对不明确的定义，拒绝猜测的诱惑 &nbsp;&nbsp;
                        虽然一开始这种方法并不是显而易见，因为你并不是Python之父 &nbsp;&nbsp;
                        做好胜过不做，但没有思考的做还不如不做 &nbsp;&nbsp;
                        如果实现很难说明，那它是个坏想法 &nbsp;&nbsp;
                        如果实现容易解释，那它有可能是个好想法 &nbsp;&nbsp;
                        命名空间是个绝妙的想法，请多加利用
                    </p>
                </div>

                {% if posts %}

                    {% for post in posts %}
                        <div class="question">
                            <div class="question-left">
                                <div class="question-image"><img src="{{ url_for("user.get_file",filename=post.user.portrait) }}"></div>
                                <div class="question-body">
                                    <div class="question-body-title"><a href="{{ url_for("main.post",post_id=post.id) }}">{{ post.title }}</a></div>
                                    <div class="question-body-add">
                                        <small><a href="#">分类</a></small>
                                        <small><a href="#">标签</a></small>
                                        <small><a href="#">{{ moment(post.timestamp).fromNow(refresh=True) }}</a></small>
                                    </div>
                                </div>
                            </div>
                            <div class="question-right">
                                <div class="question-kong"></div>
                                <div class="question-reply-number">23</div>
                            </div>
                        </div>

                    {% endfor %}

                {% endif %}


            </div>
{% endblock %}

{% block script %}
{% endblock %}

bigweb/templates/main/post.html
{% extends "base.html" %}
{% from "macros.html" import field_form %}

{% block head %}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}


{% block body %}
    <div class="post">
        <div class="post-top">
            <div class="post-left"><img src="../static/image/iii.png" alt=""></div>
            <div class="post-body">
                <a href="#" class="name">Wallace🔥👑🐅</a>
                <small class="post-body-time">4月23日&nbsp;19:23&nbsp;来自&nbsp;FDT&nbsp;www.baidu.com</small>
                <p>{{ post.article|safe }}</p>
            </div>
        </div>
        <div class="post-footer">
            <a href="#">⭐&nbsp;️收藏</a>
            <span>|</span>
            <a href="#">🤚&nbsp;分享(4)</a>
            <span>|</span>
            <a href="#">👄&nbsp;评论(26)</a>
            <span>|</span>
            <div class="dianzhan">👍&nbsp;点赞(78)</div>
        </div>
    </div>

    <div class="comment">

        <div class="comment-input">
            <div class="comment--input-image"><img src="../static/image/iii.png" alt=""></div>
            <form class="comment-input-body">
{#                {{ comment_form.csrf_token }}#}
{#                {{ field_form(comment_form.comment,cols="80", rows="2",class="text-input") }}#}
                <textarea name="text" id="" cols="80" rows="2" class="text-input"></textarea>
                <div class="comment-input-btn">
                    <a href="#">顺便转发</a>
                    <button type="button" class="btn btn-success btn-xs comment-btn" onclick="commentForm()">评论</button>
                </div>
            </form>
        </div>

        {% if post.comments %}
            {% for comment in post.comments %}
                <div class="comment-list">
                    <div class="comment-list-image"><img src="{{ url_for("user.get_file",filename=comment.post.user.portrait) }}" alt=""></div>
                    <div class="comment-list-body">
                        <div class="comment-list-top">
                            <p class="comment-p"><a href="#">{{ comment.user.username }}👌🌹：</a>{{ comment.comment }}</p>
                        </div>
                        <div class="comment-list-add">
                            <span class="comment-list-time">{{ comment.timestamp }}</span>
                            <button class="comment-list-reply">回复&nbsp;|&nbsp;👍 点赞</button>
                        </div>
                    </div>
                </div>
            {% endfor %}

        {% endif %}

    </div>




{% endblock %}



{% block bodytwo %}

<div hidden="hidden" class="post_id" >{{ post.id }}</div>

{% endblock %}




{% block script %}

    <script>

    {#var a = $(".comment-input-body");#}
    {#var post_id = $(".post_id").text();#}
    {#var value = $("textarea .text-input").var().trim();#}

    function commentForm() {

        var data = $(".text-input").val();
        $.ajax({
            type:"POST",
            url : "{{ url_for("main.comment_ajax",post_id=post.id) }}",
            data : JSON.stringify({"comment":data}),
            contentType: "application/json; charset=UTF-8",
            success : function (data) {
              alert("评论成功");
              $(".comment-list").before(data);

            }

        });
    }








    </script>


{% endblock %}